service: nestjs-graphql-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: staging
  profile: default # Config your AWS Profile
  environment: # Service wide environment variables
    NODE_ENV: production

plugins:
  - serverless-offline

package:
  patterns:
    - "!.git/**"
    - "!src/**"
    - "!test/**"
    - "!nodemon.json"
    - "!README.md"
  excludeDevDependencies: true

functions:
  index:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: "/{proxy+}"
          method: any
